### ISSUE TITLE
Dreambooth training won't save checkpoints if --save_sample_prompt is not used

### ISSUE THREAD

**Issue by fruitpudding** [CCRcmcpe/diffusers#1]
### Describe the bug

The training script won't save training results if the user doesn't specify `--save_sample_prompt` and `--n_save_sample`

I see the following codes in the script:
```
        save_sample = (args.save_sample_prompt is not None and
                       save_checkpoint or
                       args.sample_interval is not None and
                       global_step % args.sample_interval == 0)

        if not (accelerator.is_main_process and save_sample):
            return
```
Just want to make sure if it's intended:)

### Reproduction

Omit `--save_sample_prompt` and `--n_save_sample` in args of `train_dreambooth.py`

### System Info

- `diffusers` version: 0.7.0.dev0
- Platform: Linux-6.0.0-3-amd64-x86_64-with-glibc2.35
- Python version: 3.10.6
- PyTorch version (GPU?): 1.13.0+rocm5.2 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

**Comment by CCRcmcpe** [comment]
https://github.com/CCRcmcpe/diffusers/commit/d140ad4fa297fc0126e3adae253e19662d93b90f

BTW main branch is deprecated. Use yaml-config branch.
